// Small built-in Slack emoji shortcode -> Unicode map for common emoji.
// Unknown and custom workspace emoji are kept as ":name:".

const EMOJI: Record<string, string> = {
  '+1': '👍',
  thumbsup: '👍',
  '-1': '👎',
  thumbsdown: '👎',
  ok_hand: '👌',
  clap: '👏',
  pray: '🙏',
  raised_hands: '🙌',
  wave: '👋',
  muscle: '💪',
  point_up: '☝️',
  point_right: '👉',
  point_left: '👈',
  point_down: '👇',
  v: '✌️',
  handshake: '🤝',
  eyes: '👀',
  bow: '🙇',
  smile: '😄',
  smiley: '😃',
  grinning: '😀',
  laughing: '😆',
  joy: '😂',
  rolling_on_the_floor_laughing: '🤣',
  sweat_smile: '😅',
  blush: '😊',
  slightly_smiling_face: '🙂',
  upside_down_face: '🙃',
  wink: '😉',
  heart_eyes: '😍',
  kissing_heart: '😘',
  thinking_face: '🤔',
  thinking: '🤔',
  neutral_face: '😐',
  expressionless: '😑',
  no_mouth: '😶',
  smirk: '😏',
  unamused: '😒',
  face_with_rolling_eyes: '🙄',
  grimacing: '😬',
  relieved: '😌',
  pensive: '😔',
  sleepy: '😪',
  sleeping: '😴',
  mask: '😷',
  sunglasses: '😎',
  nerd_face: '🤓',
  confused: '😕',
  worried: '😟',
  slightly_frowning_face: '🙁',
  open_mouth: '😮',
  astonished: '😲',
  flushed: '😳',
  scream: '😱',
  cry: '😢',
  sob: '😭',
  sweat: '😓',
  rage: '😡',
  angry: '😠',
  exploding_head: '🤯',
  partying_face: '🥳',
  star_struck: '🤩',
  hugging_face: '🤗',
  hugs: '🤗',
  shushing_face: '🤫',
  zany_face: '🤪',
  skull: '💀',
  ghost: '👻',
  robot_face: '🤖',
  robot: '🤖',
  see_no_evil: '🙈',
  hear_no_evil: '🙉',
  speak_no_evil: '🙊',
  heart: '❤️',
  orange_heart: '🧡',
  yellow_heart: '💛',
  green_heart: '💚',
  blue_heart: '💙',
  purple_heart: '💜',
  broken_heart: '💔',
  sparkling_heart: '💖',
  fire: '🔥',
  sparkles: '✨',
  star: '⭐',
  star2: '🌟',
  boom: '💥',
  zap: '⚡',
  tada: '🎉',
  confetti_ball: '🎊',
  balloon: '🎈',
  gift: '🎁',
  trophy: '🏆',
  medal: '🏅',
  rocket: '🚀',
  '100': '💯',
  bulb: '💡',
  memo: '📝',
  pencil: '📝',
  pencil2: '✏️',
  book: '📖',
  books: '📚',
  bookmark: '🔖',
  pushpin: '📌',
  round_pushpin: '📍',
  paperclip: '📎',
  link: '🔗',
  calendar: '📆',
  date: '📅',
  clock: '🕐',
  hourglass: '⌛',
  alarm_clock: '⏰',
  email: '📧',
  envelope: '✉️',
  inbox_tray: '📥',
  outbox_tray: '📤',
  package: '📦',
  mag: '🔍',
  mag_right: '🔎',
  lock: '🔒',
  unlock: '🔓',
  key: '🔑',
  hammer: '🔨',
  wrench: '🔧',
  gear: '⚙️',
  hammer_and_wrench: '🛠️',
  computer: '💻',
  iphone: '📱',
  bug: '🐛',
  chart_with_upwards_trend: '📈',
  chart_with_downwards_trend: '📉',
  bar_chart: '📊',
  clipboard: '📋',
  file_folder: '📁',
  open_file_folder: '📂',
  bell: '🔔',
  no_bell: '🔕',
  loudspeaker: '📢',
  mega: '📣',
  speech_balloon: '💬',
  thought_balloon: '💭',
  white_check_mark: '✅',
  heavy_check_mark: '✔️',
  ballot_box_with_check: '☑️',
  x: '❌',
  negative_squared_cross_mark: '❎',
  heavy_multiplication_x: '✖️',
  warning: '⚠️',
  no_entry: '⛔',
  no_entry_sign: '🚫',
  exclamation: '❗',
  heavy_exclamation_mark: '❗',
  question: '❓',
  grey_question: '❔',
  grey_exclamation: '❕',
  bangbang: '‼️',
  interrobang: '⁉️',
  information_source: 'ℹ️',
  heavy_plus_sign: '➕',
  heavy_minus_sign: '➖',
  arrow_right: '➡️',
  arrow_left: '⬅️',
  arrow_up: '⬆️',
  arrow_down: '⬇️',
  arrows_counterclockwise: '🔄',
  repeat: '🔁',
  recycle: '♻️',
  red_circle: '🔴',
  large_blue_circle: '🔵',
  large_green_circle: '🟢',
  large_yellow_circle: '🟡',
  white_circle: '⚪',
  black_circle: '⚫',
  o: '⭕',
  new: '🆕',
  free: '🆓',
  up: '🆙',
  cool: '🆒',
  ok: '🆗',
  sos: '🆘',
  checkered_flag: '🏁',
  triangular_flag_on_post: '🚩',
  construction: '🚧',
  rotating_light: '🚨',
  moneybag: '💰',
  dollar: '💵',
  yen: '💴',
  credit_card: '💳',
  coffee: '☕',
  beer: '🍺',
  beers: '🍻',
  pizza: '🍕',
  cake: '🍰',
  sushi: '🍣',
  ramen: '🍜',
  rice: '🍚',
  bento: '🍱',
  sun: '☀️',
  sunny: '☀️',
  cloud: '☁️',
  umbrella: '☂️',
  snowflake: '❄️',
  rainbow: '🌈',
  earth_asia: '🌏',
  globe_with_meridians: '🌐',
  house: '🏠',
  office: '🏢',
  car: '🚗',
  airplane: '✈️',
  train: '🚆',
  dog: '🐶',
  cat: '🐱',
  panda_face: '🐼',
  crossed_fingers: '🤞',
  facepalm: '🤦',
  shrug: '🤷',
  raising_hand: '🙋',
  ok_woman: '🙆',
  no_good: '🙅',
  man_bowing: '🙇',
  woman_bowing: '🙇‍♀️',
  sweat_drops: '💦',
  zzz: '💤',
  dash: '💨',
  sparkle: '❇️',
  eight_spoked_asterisk: '✳️',
  one: '1️⃣',
  two: '2️⃣',
  three: '3️⃣',
  four: '4️⃣',
  five: '5️⃣',
  six: '6️⃣',
  seven: '7️⃣',
  eight: '8️⃣',
  nine: '9️⃣',
  keycap_ten: '🔟',
  zero: '0️⃣',
  hourglass_flowing_sand: '⏳',
  stopwatch: '⏱️',
  alien: '👽',
  poop: '💩',
  hankey: '💩',
  money_with_wings: '💸',
  gem: '💎',
  crown: '👑',
  dart: '🎯',
  game_die: '🎲',
  art: '🎨',
  musical_note: '🎵',
  notes: '🎶',
  camera: '📷',
  movie_camera: '🎥',
  tv: '📺',
  headphones: '🎧',
  microphone: '🎤',
  telephone_receiver: '📞',
  phone: '☎️',
  point_up_2: '👆',
  writing_hand: '✍️',
  saluting_face: '🫡',
  melting_face: '🫠',
  face_holding_back_tears: '🥹',
  pleading_face: '🥺',
  smiling_face_with_tear: '🥲',
  yum: '😋',
  innocent: '😇',
  money_mouth_face: '🤑',
  heavy_heart_exclamation_mark_ornament: '❣️',
  ok_man: '🙆‍♂️',
  japan: '🗾',
  jp: '🇯🇵',
  vn: '🇻🇳',
  us: '🇺🇸',
};

/** Resolve a Slack emoji name (without colons) to Unicode, or null if unknown. */
export function emojiToUnicode(name: string): string | null {
  // Slack sends skin tones as a separate suffix, e.g. "+1::skin-tone-2".
  const base = name.replace(/::skin-tone-\d$/, '');
  return EMOJI[base] ?? null;
}

/** Convert a Slack emoji name to Unicode, keeping ":name:" when unknown. */
export function renderEmoji(name: string, unicodeHex?: string): string {
  if (unicodeHex) {
    try {
      const codepoints = unicodeHex.split('-').map((h) => parseInt(h, 16));
      if (codepoints.length > 0 && codepoints.every((c) => Number.isFinite(c) && c > 0)) {
        return String.fromCodePoint(...codepoints);
      }
    } catch {
      // fall through to the name lookup
    }
  }
  return emojiToUnicode(name) ?? `:${name}:`;
}

/** Replace ":name:" (optionally followed by ":skin-tone-N:") in plain text. */
export function replaceEmojiShortcodes(text: string): string {
  return text.replace(/:([a-z0-9_+'-]+):(?::skin-tone-\d:)?/g, (match, name: string) => {
    const uni = emojiToUnicode(name);
    return uni ?? match;
  });
}
